# apiVersion: kafka.strimzi.io/v1
# kind: KafkaConnector
# metadata:
#   name: couchbase-source
#   namespace: cardserver
#   labels:
#     strimzi.io/cluster: cardserver
# spec:
#   class: com.couchbase.connect.kafka.CouchbaseSourceConnector
#   tasksMax: 2
#   config:
#     couchbase.topic: "couchbase-cardserver-events"
#     couchbase.seed.nodes: "couchbase.couchbase.svc.cluster.local"
#     couchbase.username: "root"
#     couchbase.password: "killer"
#     couchbase.bucket: "cardserver"
#     couchbase.source.handler: "com.couchbase.connect.kafka.handler.source.RawJsonSourceHandler"
#     key.converter: "org.apache.kafka.connect.storage.StringConverter"
#     value.converter: "org.apache.kafka.connect.converters.ByteArrayConverter"

