---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: connect-cluster-cardserver-configs
  namespace: cardserver
  labels:
    strimzi.io/cluster: cardserver
spec:
  partitions: 1 # Configs MUST be exactly 1 partition
  replicas: 3
  config:
    cleanup.policy: compact
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: connect-cluster-cardserver-offsets
  namespace: cardserver
  labels:
    strimzi.io/cluster: cardserver
spec:
  partitions: 25 # Standard default for offsets
  replicas: 3
  config:
    cleanup.policy: compact
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: connect-cluster-cardserver-status
  namespace: cardserver
  labels:
    strimzi.io/cluster: cardserver
spec:
  partitions: 5 # Standard default for status
  replicas: 3
  config:
    cleanup.policy: compact
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: couchbase-cardserver-events
  namespace: cardserver
  labels:
    strimzi.io/cluster: cardserver
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 60000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: gameevents
  namespace: cardserver
  labels:
    strimzi.io/cluster: cardserver
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 60000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: ssetopic
  namespace: cardserver
  labels:
    strimzi.io/cluster: cardserver
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 60000
    segment.bytes: 1073741824
