# apiVersion: kafka.strimzi.io/v1
# kind: KafkaConnect
# metadata:
#   name: cardserver
#   namespace: cardserver
#   annotations:
#     strimzi.io/use-connector-resources: "true"
# spec:
#   version: 4.3.0
#   replicas: 1
#   bootstrapServers: cardserver-kafka-bootstrap:9092

#   groupId: kafka-connect-cardserver-couchbase
#   configStorageTopic: connect-cluster-cardserver-configs
#   statusStorageTopic: connect-cluster-cardserver-status
#   offsetStorageTopic: connect-cluster-cardserver-offsets

#   image: ghcr.io/bhuism/kafka-connect-couchbase:2.0.0
