apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: gameEventTrigger
  namespace: cardserver
spec:
  broker: default
  filters:
    - exact:
        type: gameEvent
  subscriber:
    uri: http://cardserver-gameengine.cardserver.svc.cluster.local:8083/gameEvent
