apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: couchbaseCardserverEvents
  namespace: cardserver
spec:
  broker: default
  filters:
    - exact:
        type: couchbaseCardserverEvents
  subscriber:
    uri: http://cardserver-aiplayer.cardserver.svc.cluster.local:8084/couchbaseCardserverEvents
