apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: bind-spring-boot-to-broker
  namespace: cardserver
spec:
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default
  subject:
    apiVersion: apps/v1
    kind: Deployment
    selector:
      matchLabels:
        app.kubernetes.io/name: cardserver
