apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-display
  namespace: cardserver
spec:
  template:
    metadata:
      annotations:
        # Forces Knative to always keep at least 1 pod running
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - image: gcr.io/knative-releases/knative.dev/eventing/cmd/event_display
