apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: couchbase-cardserver-events-trigger-aiplayer
  namespace: cardserver
spec:
  broker: default
  filters:
    - exact:
        type: dev.knative.kafka.event
        source: /apis/v1/namespaces/cardserver/kafkasources/cardserver-kafka-source#couchbase-cardserver-events
  subscriber:
    uri: http://cardserver-aiplayer.cardserver.svc.cluster.local:8084/couchbaseCardserverEvents
