apiVersion: sources.knative.dev/v1
kind: KafkaSource
metadata:
  name: cardserver-kafka-source
  namespace: cardserver
spec:
  consumerGroup: knative-group
  bootstrapServers:
   - cardserver-kafka-bootstrap:9092
  topics:
   - couchbase-cardserver-events
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default
