apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: route-order-creation
  namespace: cardserver
spec:
  broker: default
  filter:
    attributes:
      type: order.created
  subscriber:
    uri: http://cardserver-api.cardserver.svc.cluster.local:8080/processOrder
