apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: route-order-creation
  namespace: cardserver
spec:
  broker: default
  filter:
    attributes:
      type: order.created
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: cardserver-api
