apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: route-order-creation
  namespace: cardserver
spec:
  broker: default
  filter:
    exact:
      type: gameEvent
  subscriber:
    uri: http://cardserver-gameengine.cardserver.svc.cluster.local:8080/gameEvent
