apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  project: default
  source:
    repoURL: oci://ghcr.io/codecentric/helm-charts/keycloakx
    chart: keycloakx
    targetRevision: 7.1.11
    helm:
      valuesObject:
        replicas: 1
        revisionHistoryLimit: 1
        restartPolicy: Always

        command:
          - /opt/keycloak/bin/kc.sh
        args:
          - start

        extraEnv: |
          - name: KC_LOG_LEVEL
            value: INFO
          - name: KC_HOSTNAME
            value: https://auth.impl.nl
          - name: KC_HOSTNAME_ADMIN
            value: https://keycloak.impl.nl
          - name: KC_PROXY_HEADERS
            value: xforwarded
          # - name: KC_HTTP_ENABLED
          #   value: "true"
          # - name: kc_http_management_relative_path
          #   value: /auth/admin
          - name: KC_BOOTSTRAP_ADMIN_USERNAME
            value: admin
          - name: KC_BOOTSTRAP_ADMIN_PASSWORD
            value: admin

        ingress:
          enabled: true
          ingressClassName: nginx-external
          servicePort: http
          annotations:
            external-dns.alpha.kubernetes.io/target: jasmine.odee.net
            external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
            cert-manager.io/cluster-issuer: letsencrypt-production
            nginx.ingress.kubernetes.io/proxy-buffer-size: "128k" # Prevents big header errors with tokens
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
          labels: {}
          rules:
            - host: auth.impl.nl
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: auth.impl.nl
              hosts:
                - auth.impl.nl

          # ingress for console only (/auth/admin)
          console:
            # If `true`, an Ingress is created for console path only
            enabled: true
            # The name of Ingress Class associated with the console ingress only
            ingressClassName: nginx-internal
            # Ingress annotations for console ingress only
            # Useful to set nginx.ingress.kubernetes.io/whitelist-source-range particularly
            annotations:
              external-dns.alpha.kubernetes.io/target: ingress-internal.impl.nl
              external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
              cert-manager.io/cluster-issuer: letsencrypt-production
              gethomepage.dev/enabled: "true"
              nginx.ingress.kubernetes.io/proxy-buffer-size: "128k" # Prevents big header errors with tokens
              nginx.ingress.kubernetes.io/ssl-redirect: "true"
            labels: {}
            rules:
              - host: keycloak.impl.nl
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - secretName: keycloak.impl.nl
                hosts:
                  - keycloak.impl.nl

        dbchecker:
          enabled: false
          image:
            # Docker image used to check Database readiness at startup
            repository: docker.io/busybox
            # Image tag for the dbchecker image
            tag: 1.37
            # Image pull policy for the dbchecker image
            pullPolicy: IfNotPresent
          # SecurityContext for the dbchecker container
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
          # Resource requests and limits for the dbchecker container
          resources:
            requests:
              cpu: "20m"
              memory: "32Mi"
            limits:
              cpu: "20m"
              memory: "32Mi"

        database:
          vendor: postgres
          hostname: postgresql-rw.cloudnative-pg
          port: 5432
          database: keycloak
          username: keycloak
          password: killer

        cache:
          # Use "custom" to disable automatic cache configuration
          stack: default

        proxy:
          enabled: false

        metrics:
          enabled: true

        health:
          enabled: true

        http:
          relativePath: "/"
        #   internalPort: http-internal
        #   internalScheme: HTTP

        serviceMonitor:
          enabled: true

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
