apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: technitium-config
  namespace: technitium
spec:
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
  accessModes:
    - ReadWriteMany
  storageClassName: cephfs
