controllers:
  api:
    replicas: 2
    revisionHistoryLimit: 1
    strategy: RollingUpdate
    rollingUpdate:
      unavailable: 0
    containers:
      api:
        image:
          repository: ghcr.io/bhuism/api
          tag: "latest"
          pullPolicy: Always
        probes:
          liveness:
            enabled: true
            type: HTTP
            path: /manage/health/liveness
            port: 9080
            spec:
              initialDelaySeconds: 15
              timeoutSeconds: 5
              periodSeconds: 10
              failureThreshold: 3
          readiness:
            enabled: true
            type: HTTP
            path: /manage/health/readiness
            port: 9080
            spec:
              initialDelaySeconds: 15
              timeoutSeconds: 5
              periodSeconds: 10
              failureThreshold: 3
          startup:
            enabled: true
            port: 9080
            spec:
              initialDelaySeconds: 15
              timeoutSeconds: 5
              periodSeconds: 3
              failureThreshold: 10
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
        resources:
          limits:
            cpu: 2
            memory: 1500Mi
          requests:
            cpu: 1
            memory: 1500Mi
        env:
          SPRING_PROFILES_ACTIVE: production
          CARDSERVER_AUTH_JWT_ES512_SECRET:
            valueFrom:
              secretKeyRef:
                name: jwtsecret
                key: jwtes512secretvalue
  couchbase2redis:
    replicas: 1
    revisionHistoryLimit: 1
    strategy: Recreate
    containers:
      couchbase2redis:
        image:
          repository: ghcr.io/bhuism/couchbase2redis
          tag: "latest"
          pullPolicy: Always
        probes:
          liveness:
            enabled: true
            type: HTTP
            path: /manage/health/liveness
            port: 9081
            spec:
              initialDelaySeconds: 15
              timeoutSeconds: 5
              periodSeconds: 10
              failureThreshold: 3
          readiness:
            enabled: true
            type: HTTP
            path: /manage/health/readiness
            port: 9081
            spec:
              initialDelaySeconds: 15
              timeoutSeconds: 5
              periodSeconds: 10
              failureThreshold: 3
          startup:
            enabled: true
            port: 9081
            spec:
              initialDelaySeconds: 15
              timeoutSeconds: 5
              periodSeconds: 3
              failureThreshold: 10
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
        resources:
          limits:
            cpu: 2
            memory: 1500Mi
          requests:
            cpu: 1
            memory: 1500Mi
        env:
          SPRING_PROFILES_ACTIVE: production
  stream:
    replicas: 2
    revisionHistoryLimit: 1
    strategy: RollingUpdate
    rollingUpdate:
      unavailable: 0
    containers:
      stream:
        image:
          repository: ghcr.io/bhuism/stream
          tag: "latest"
          pullPolicy: Always
        probes:
          liveness:
            enabled: true
            type: HTTP
            path: /manage/health/liveness
            port: 9082
            spec:
              initialDelaySeconds: 15
              timeoutSeconds: 5
              periodSeconds: 10
              failureThreshold: 3
          readiness:
            enabled: true
            type: HTTP
            path: /manage/health/readiness
            port: 9082
            spec:
              initialDelaySeconds: 15
              timeoutSeconds: 5
              periodSeconds: 10
              failureThreshold: 3
          startup:
            enabled: true
            port: 9082
            spec:
              initialDelaySeconds: 15
              timeoutSeconds: 5
              periodSeconds: 3
              failureThreshold: 10
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
        resources:
          limits:
            cpu: 2
            memory: 1500Mi
          requests:
            cpu: 1
            memory: 1500Mi
        env:
          SPRING_PROFILES_ACTIVE: production
  gameengine:
    replicas: 2
    revisionHistoryLimit: 1
    strategy: RollingUpdate
    rollingUpdate:
      unavailable: 0
    containers:
      stream:
        image:
          repository: ghcr.io/bhuism/gameengine
          tag: "latest"
          pullPolicy: Always
        probes:
          liveness:
            enabled: true
            type: HTTP
            path: /manage/health/liveness
            port: 9083
            spec:
              initialDelaySeconds: 15
              timeoutSeconds: 5
              periodSeconds: 10
              failureThreshold: 3
          readiness:
            enabled: true
            type: HTTP
            path: /manage/health/readiness
            port: 9083
            spec:
              initialDelaySeconds: 15
              timeoutSeconds: 5
              periodSeconds: 10
              failureThreshold: 3
          startup:
            enabled: true
            port: 9083
            spec:
              initialDelaySeconds: 15
              timeoutSeconds: 5
              periodSeconds: 3
              failureThreshold: 10
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
        resources:
          limits:
            cpu: 2
            memory: 1500Mi
          requests:
            cpu: 1
            memory: 1500Mi
        env:
          SPRING_PROFILES_ACTIVE: production
  aiplayer:
    replicas: 1
    revisionHistoryLimit: 1
    strategy: RollingUpdate
    rollingUpdate:
      unavailable: 0
    containers:
      stream:
        image:
          repository: ghcr.io/bhuism/aiplayer
          tag: "latest"
          pullPolicy: Always
        probes:
          liveness:
            enabled: true
            type: HTTP
            path: /manage/health/liveness
            port: 9084
            spec:
              initialDelaySeconds: 15
              timeoutSeconds: 5
              periodSeconds: 10
              failureThreshold: 3
          readiness:
            enabled: true
            type: HTTP
            path: /manage/health/readiness
            port: 9084
            spec:
              initialDelaySeconds: 15
              timeoutSeconds: 5
              periodSeconds: 10
              failureThreshold: 3
          startup:
            enabled: true
            port: 9084
            spec:
              initialDelaySeconds: 15
              timeoutSeconds: 5
              periodSeconds: 3
              failureThreshold: 10
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
        resources:
          limits:
            cpu: 2
            memory: 1500Mi
          requests:
            cpu: 1
            memory: 1500Mi
        env:
          SPRING_PROFILES_ACTIVE: production
  admin:
    replicas: 1
    revisionHistoryLimit: 1
    containers:
      stream:
        image:
          repository: ghcr.io/bhuism/admin
          tag: "latest"
          pullPolicy: Always
        probes:
          liveness:
            enabled: true
            type: HTTP
            path: /manage/health/liveness
            port: 9085
            spec:
              initialDelaySeconds: 15
              timeoutSeconds: 5
              periodSeconds: 10
              failureThreshold: 3
          readiness:
            enabled: true
            type: HTTP
            path: /manage/health/readiness
            port: 9085
            spec:
              initialDelaySeconds: 15
              timeoutSeconds: 5
              periodSeconds: 10
              failureThreshold: 3
          startup:
            enabled: true
            port: 9085
            spec:
              initialDelaySeconds: 15
              timeoutSeconds: 5
              periodSeconds: 3
              failureThreshold: 10
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
        resources:
          limits:
            cpu: 2
            memory: 1500Mi
          requests:
            cpu: 1
            memory: 1500Mi
        env:
          SPRING_PROFILES_ACTIVE: production
          LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: trace
service:
  aiplayer:
    controller: aiplayer
    ports:
      adminport:
        port: 9084
  gameengine:
    controller: gameengine
    ports:
      adminport:
        port: 9083
  admin:
    controller: admin
    ports:
      http:
        port: 8085
  api:
    controller: api
    ports:
      http:
        port: 8080
      adminport:
        port: 9080
  stream:
    controller: stream
    ports:
      http:
        port: 8082
      adminport:
        port: 9082
  couchbase2redis:
    controller: couchbase2redis
    ports:
      adminport:
        port: 9081

ingress:
  mainingress:
    className: nginx-external
    annotations:
      external-dns.alpha.kubernetes.io/target: jasmine.odee.net
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
      cert-manager.io/cluster-issuer: letsencrypt-production
      gethomepage.dev/enabled: "true"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-buffering: "off"
      nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    hosts:
      - host: api.klaversjassen.nl
        paths:
          - path: /
            service:
              identifier: api
              port: http
      - host: stream.klaversjassen.nl
        paths:
          - path: /
            service:
              identifier: stream
              port: http
      - host: admin.klaversjassen.nl
        paths:
          - path: /
            service:
              identifier: admin
              port: http
    tls:
      - secretName: api.klaversjassen.nl
        hosts:
          - api.klaversjassen.nl
      - secretName: stream.klaversjassen.nl
        hosts:
          - stream.klaversjassen.nl
      - secretName: admin.klaversjassen.nl
        hosts:
          - admin.klaversjassen.nl
