apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-storage
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: local-path-storage
  project: default
  source:
    chart: deploy/chart/local-path-provisioner
    repoURL: https://github.com/rancher/local-path-provisioner.git
    targetRevision: v0.0.36
    helm:
      valuesObject:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
    syncOptions:
      - CreateNamespace=true
