# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: kafka-pvc
#   namespace: kafka
# spec:
#   volumeMode: Filesystem
#   resources:
#     requests:
#       storage: 8Gi
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: ceph-rbd
