apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-operator
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  project: default
  source:
    chart: strimzi-kafka-operator
    repoURL: https://strimzi.io/charts/
    targetRevision: 1.1.0
    helm:
      valuesObject:
        watchNamespaces:
          - cardserver
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
