{
 "title": "Smartmeter",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "power (sum phases)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "sum(gotsmart_active_power_delivered_l1_kw+gotsmart_active_power_delivered_l2_kw+gotsmart_active_power_delivered_l3_kw)",
     "legendFormat": "verbruik"
    },
    {
     "expr": "-sum(gotsmart_active_power_received_l1_kw+gotsmart_active_power_received_l2_kw+gotsmart_active_power_received_l3_kw)",
     "legendFormat": "levering"
    }
   ]
  },
  {
   "title": "power (total)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "sum(gotsmart_electricity_power_delivered_kw)",
     "legendFormat": "delivered"
    },
    {
     "expr": "-sum(gotsmart_electricity_power_received_kw)",
     "legendFormat": "received"
    }
   ]
  },
  {
   "title": "power by rate (tariff 1+2)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "(sum(rate(gotsmart_electricity_delivered_to_client_tariff_1_kwh[$__rate_interval]))+sum(rate(gotsmart_electricity_delivered_to_client_tariff_2_kwh[$__rate_interval])))*4000",
     "legendFormat": "delivered to client"
    },
    {
     "expr": "(-sum(rate(gotsmart_electricity_delivered_by_client_tariff_1_kwh[$__rate_interval]))-sum(rate(gotsmart_electricity_delivered_by_client_tariff_2_kwh[$__rate_interval])))*4000",
     "legendFormat": "delivered by client"
    }
   ]
  },
  {
   "title": "Spanning en Stroom",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Voltage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      { "expr": "sum(gotsmart_voltage_l1_v)", "legendFormat": "L1" },
      { "expr": "sum(gotsmart_voltage_l2_v)", "legendFormat": "L2" },
      { "expr": "sum(gotsmart_voltage_l3_v)", "legendFormat": "L3" }
     ]
    },
    {
     "title": "Current (in or out)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      { "expr": "sum(gotsmart_current_l1_a)", "legendFormat": "l1" },
      { "expr": "sum(gotsmart_current_l2_a)", "legendFormat": "l2" },
      { "expr": "sum(gotsmart_current_l3_a)", "legendFormat": "l3" }
     ]
    }
   ]
  },
  {
   "title": "Stroom storingen",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "totaal aantal stroomstoringen",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(gotsmart_power_failures_total)",
       "legendFormat": "verstoringen"
      },
      {
       "expr": "sum(gotsmart_long_power_failures_total)",
       "legendFormat": "lange verstoringen"
      }
     ]
    },
    {
     "title": "huidige elektriciteitsverbruik kW",
     "type": "stat",
     "gridPos": { "h": 9, "w": 5, "x": 8, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(gotsmart_electricity_delivered_to_client_tariff_1_kwh)",
       "legendFormat": "tariff 1"
      },
      {
       "expr": "sum(gotsmart_electricity_delivered_to_client_tariff_2_kwh)",
       "legendFormat": "tariff 2"
      }
     ]
    },
    {
     "title": "huidige elektriciteitsverbruik kW (som phases)",
     "type": "stat",
     "gridPos": { "h": 9, "w": 4, "x": 13, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "kwatt" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(gotsmart_active_power_delivered_l1_kw+gotsmart_active_power_delivered_l2_kw+gotsmart_active_power_delivered_l3_kw)"
      }
     ]
    },
    {
     "title": "huidige elektriciteitsverbruik kW",
     "type": "stat",
     "gridPos": { "h": 9, "w": 4, "x": 17, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "kwatt" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(gotsmart_electricity_power_delivered_kw)"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 9, "w": 3, "x": 21, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "kwatt" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(gotsmart_active_power_delivered_l1_kw)",
       "legendFormat": "l1"
      },
      {
       "expr": "sum(gotsmart_active_power_delivered_l2_kw)",
       "legendFormat": "l2"
      },
      {
       "expr": "sum(gotsmart_active_power_delivered_l3_kw)",
       "legendFormat": "l3"
      }
     ]
    }
   ]
  }
 ]
}