apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spring-boot-admin-pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "endpoints", "services"]
    verbs: ["get", "list", "watch"]

