#!/bin/sh

#PASSWORD=$(argocd account bcrypt --password x)

kubectl -n argocd patch secret argocd-secret \
  -p '{"stringData": {
    "admin.password": "$2a$10$5u6krYWHwKmqRX/wIfWbKOzZDPLNX2TaSEXeoEaKZ4liQpot972eu",
    "admin.passwordMtime": "'$(date +%FT%T%Z)'"
  }}'
  