#!/bin/sh

kubectl run -i --rm --tty debian2 -n star-arr --overrides='
{
  "apiVersion": "v1",
      "spec": {
        "containers": [
          {
            "name": "debian",
            "image": "debian",
            "args": [
              "bash"
            ],
            "stdin": true,
            "stdinOnce": true,
            "tty": true,
            "volumeMounts": [{
              "mountPath": "/mnt/media",
              "name": "media"
            },{
              "mountPath": "/mnt/download",
              "name": "download"
            }]
          }
        ],
        "volumes": [{
          "name":"media",
          "persistentVolumeClaim":{
		"claimName": "media-pvc"
	}
        },{
          "name":"download",
          "persistentVolumeClaim":{
		"claimName": "download-pvc"
	}
        }
        ]
      }
}
'  --image=debian --restart=Never -- bash
