#!/bin/sh

kubectl run -i --rm --tty debian -n headscale --overrides='
{
  "apiVersion": "v1",
      "spec": {
        "containers": [
          {
            "name": "debian",
            "image": "debian",
            "args": [
              "bash"
            ],
            "stdin": true,
            "stdinOnce": true,
            "tty": true,
            "volumeMounts": [{
              "mountPath": "/mnt/config",
              "name": "disk1"
            },{
              "mountPath": "/mnt/data",
              "name": "disk2"
            }]
          }
        ],
        "volumes": [{
          "name":"disk1",
          "persistentVolumeClaim":{
		"claimName": "headscale-config"
	}
        },{
          "name":"disk2",
          "persistentVolumeClaim":{
		"claimName": "headscale-data"
	}
        }
        ]
      }
}
'  --image=debian --restart=Never -- bash
