#!/bin/sh

set -e
set -x


read -r -p "Upgrading all nodes, are you sure? ctrl-c to cancel" key

for i in 182 196 183 197 24 25 26 27 ; do

talosctl -n 192.168.1.$i upgrade -i ghcr.io/nberlee/installer:v1.7.2-rk3588

sleep 1m

done

