apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 9.5.14
    helm:
      valuesObject:
        dex:
          enabled: false
        repoServer:
          metrics:
            enabled: true
          env:
            - name: SSL_CERT_DIR
              value: "/app/config/tls/"
        server:
          metrics:
            enabled: true
          env:
            - name: SSL_CERT_DIR
              value: "/app/config/tls/"
          extraArgs:
            - --insecure
          config:
            repositories: |
              - type: helm
                name: argo-cd
                url: https://argoproj.github.io/argo-helm
          redis:
            metrics:
              enabled: false
          ingress:
            enabled: true
            ingressClassName: nginx-internal
            annotations:
              external-dns.alpha.kubernetes.io/target: ingress-internal.impl.nl
              external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
              cert-manager.io/cluster-issuer: letsencrypt-production
              gethomepage.dev/enabled: "true"
            hostname: argocd.impl.nl
            tls: true

        applicationSet:
          metrics:
            enabled: true
        notifications:
          metrics:
            enabled: true
        controller:
          metrics:
            enabled: true
        configs:
          cm:
            resource.customizations.ignoreDifferences.apps_Deployment: |
              jsonPointers:
              - /spec/template/spec/hostUsers
            resource.customizations.ignoreDifferences.apps_StatefulSet: |
              jsonPointers:
              - /spec/template/spec/hostUsers
            admin.enabled: true
            application.resourceTrackingMethod: annotation+label
            url: https://argocd.impl.nl
            oidc.config: |
              name: Keycloak
              issuer: https://auth.impl.nl/realms/impl
              clientID: main
              enablePKCEAuthentication: true
              refreshTokenThreshold: 2m
              requestedScopes: ["openid", "profile", "email"]
          rbac:
            create: true
            policy.default: role:readonly
            # policy.csv: |
            #   g, bhuism@odee.net, role:admin
            scopes:
              - openid
              - profile
              - email
          params:
            application.namespaces: "*"
            server.insecure: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
